# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: .ci/gitlab/ci.yml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json
    -   id: check-symlinks
    -   id: check-added-large-files
    -   id: debug-statements
        exclude: "src/pymor/algorithms/rules.py"
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings, flake8-rst-docstrings]
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.4.0
  hooks:
  - id: markdownlint-cli2
