---
contact_links:
  - name: GitHub Discussions
    url: https://github.com/pymor/pymor/discussions
    about: A good place to ask questions about how to use pyMOR or other pyMOR-related
      topics.
