---
name: Add Labels
on:
  - pull_request_target
jobs:
  # This action will triage pull requests and apply a label based on the
  # paths that are modified in the pull request.
  # https://github.com/actions/labeler/blob/main/README.md
  Labeler:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
